const products=[
 {id:1,name:'Подвижная собака',desc:'3D-печать · подвижная модель',price:400,category:'figures',badge:'Новинка',image:'assets/dog.svg'},
 {id:2,name:'Подвижная ящерица',desc:'3D-печать · гибкая модель',price:300,category:'figures',image:'assets/lizard.svg'},
 {id:3,name:'Свисток двойной',desc:'3D-печать · двойной тон',price:200,category:'whistles',badge:'Громкий',image:'assets/whistle-double.svg'},
 {id:4,name:'Свисток одинарный',desc:'3D-печать · одинарный тон',price:150,category:'whistles',image:'assets/whistle-single.svg'},
 {id:5,name:'Хомяк маленький',desc:'3D-печать · мини-фигурка',price:150,category:'figures',badge:'Мини',image:'assets/hamster.svg'}
];
let cart=JSON.parse(localStorage.getItem('forma-cart')||'{}');
cart=Object.fromEntries(Object.entries(cart).filter(([id])=>products.some(p=>p.id==id)));
localStorage.setItem('forma-cart',JSON.stringify(cart));
const themeToggle=document.querySelector('#themeToggle');
const savedTheme=localStorage.getItem('3d-shop-theme');
const preferredDark=window.matchMedia('(prefers-color-scheme: dark)').matches;
function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('3d-shop-theme',theme);const dark=theme==='dark';themeToggle.querySelector('.theme-icon').textContent=dark?'☀':'☾';themeToggle.setAttribute('aria-label',dark?'Включить светлую тему':'Включить тёмную тему')}
setTheme(savedTheme||(preferredDark?'dark':'light'));
themeToggle.addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
const rub=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
function renderProducts(filter='all'){const shown=products.filter(p=>filter==='all'||p.category===filter);document.querySelector('#productGrid').innerHTML=shown.map(p=>`<article class="product-card"><div class="product-image">${p.badge?`<span class="badge">${p.badge}</span>`:''}<img src="${p.image}" alt="${p.name}"></div><div class="product-info"><div><h3>${p.name}</h3><p>${p.desc}</p></div><strong>${rub(p.price)}</strong><button class="add" data-add="${p.id}">Добавить в корзину</button></div></article>`).join('');document.querySelector('#catalogEmpty').hidden=shown.length>0}
function save(){localStorage.setItem('forma-cart',JSON.stringify(cart));renderCart()}
function renderCart(){const entries=Object.entries(cart).filter(([,q])=>q>0);const total=entries.reduce((s,[id,q])=>s+products.find(p=>p.id==id).price*q,0);const count=entries.reduce((s,[,q])=>s+q,0);document.querySelector('#cartCount').textContent=count;document.querySelector('#cartEmpty').hidden=!!entries.length;document.querySelector('#cartFooter').hidden=!entries.length;document.querySelector('#cartItems').innerHTML=entries.map(([id,q])=>{const p=products.find(x=>x.id==id);return `<div class="cart-item"><img src="${p.image}" alt=""><div><h3>${p.name}</h3><p>${p.desc}</p><div class="qty"><button data-change="${id}" data-delta="-1">−</button><span>${q}</span><button data-change="${id}" data-delta="1">+</button></div></div><div><strong>${rub(p.price*q)}</strong><button class="remove" data-remove="${id}" aria-label="Удалить">×</button></div></div>`}).join('');document.querySelector('#cartTotal').textContent=rub(total);const left=Math.max(0,10000-total);document.querySelector('#deliveryLeft').textContent=left?rub(left):'Бесплатно';document.querySelector('#deliveryBar').style.width=Math.min(100,total/100)+'%';document.querySelector('#telegramOrder').href='https://t.me/andrewshpik'}
function toggleCart(show){document.querySelector('#cart').classList.toggle('open',show);document.querySelector('#overlay').classList.toggle('open',show);document.querySelector('#cart').setAttribute('aria-hidden',!show);document.body.style.overflow=show?'hidden':''}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){cart[add.dataset.add]=(cart[add.dataset.add]||0)+1;save();const t=document.querySelector('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500)}const ch=e.target.closest('[data-change]');if(ch){cart[ch.dataset.change]=(cart[ch.dataset.change]||0)+Number(ch.dataset.delta);if(cart[ch.dataset.change]<=0)delete cart[ch.dataset.change];save()}const rm=e.target.closest('[data-remove]');if(rm){delete cart[rm.dataset.remove];save()}if(e.target.closest('[data-close-cart]'))toggleCart(false)});
document.querySelector('#cartOpen').onclick=()=>toggleCart(true);document.querySelector('#cartClose').onclick=()=>toggleCart(false);document.querySelector('#overlay').onclick=()=>toggleCart(false);document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts(b.dataset.filter)});document.addEventListener('keydown',e=>{if(e.key==='Escape')toggleCart(false)});renderProducts();renderCart();
